// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVuUk96JtpwZLFVG4fV9sW3FLh1277E0',
    appId: '1:492098592099:android:fdeb546eada60ceba78756',
    messagingSenderId: '492098592099',
    projectId: 'loker-65a52',
    storageBucket: 'gs://attendance-e0a2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyChVuUk96JtpwZLFVG4fV9sW3FLh1277E0',
    appId: '1:492098592099:android:fdeb546eada60ceba78756',
    messagingSenderId: '492098592099',
    projectId: 'attendance-e0a2a',
    storageBucket: 'gs://attendance-e0a2a.appspot.com',
    androidClientId: '403064089399-arrn7dmiuflnsmi2piboirrvjrmviisb.apps.googleusercontent.com',
    iosClientId: '403064089399-ofsc4ts7siul9vk0j5evlm5vcfh31u7i.apps.googleusercontent.com',
    iosBundleId: 'com.shokhrukhbek.nectar',
  );
}
